# -*- encoding: utf-8 -*-

defaults: &defaults
  enju:
    web_hostname: 'localhost' 
    web_port_number: 3000

  header:
    # 現在日付の表示 0:非表示 1:西暦 2:和暦
    disp_date: 2

  # フォームに入力済みの状態で、ファンクションキーによる画面遷移を行おうとするとアラート面を表示
  disp_alert_when_move_page_with_function: true

  # パトロンの名前を入力する際、姓を先に表示する
  family_name_first: true
  
  max_number_of_results: 500
  write_search_log_to_file: true
  csv_charset_conversion: true

  # template file for import
  resource_import_template: "templates/resource_import_template.zip"
  
  # 無操作待機時間 (sec)
  #no_operation_counter: 300
  no_operation_counter: 0

  # Choose a locale from 'ca', 'de', 'fr', 'jp', 'uk', 'us'
  # #AMAZON_AWS_HOSTNAME = 'ecs.amazonaws.com'
  amazon:
    aws_hostname: ecs.amazonaws.jp
    hostname: www.amazon.co.jp
    access_key: REPLACE_WITH_YOUR_AMAZON_ACCESS_KEY
    secret_access_key: REPLACE_WITH_YOUR_AMAZON_SECRET_ACCESS_KEY

  # :google, :amazon
  book_jacket:
    source: :google
    unknown_resource:

  # :mozshot, :simpleapi, :heartrails, :thumbalizr
  screenshot:
    generator: :mozshot

  uploaded_file:
      storage: :local

  # set disp column of checkins 
  checkins:
    disp_title: true
    disp_user: true

  # set disp column of checked_items
  checked_items:
    disp_title: true
    disp_user: true

  uploaded_file:
    storage:

  # refs 3861 資料の詳細検索時、各項目に関しANDで検索を行うか
  advanced_search:
    use_and: true

  manifestations:
    # refs 2601 すべてのユーザに検索結果の一覧の取得が出来るようにする
    users_show_output_button: false
    # refs 3806 資料の検索結果一覧の表示件数のセレクタ値
    per_page: '10, 20, 50, 100'
    # refs 4078 検索：結果の表示は書誌と文献でわける
    split_by_type: true

  send_message:
    # refs 2506 予約受付時に予約者に受付完了メッセージを送信するか
    reservation_accepted_for_patron: true

    # refs 2506 予約受付時に管理者に受付完了メッセージを送信するか
    reservation_accepted_for_library: true

    # refs 2506 予約キャンセル時に予約者にキャンセル完了メッセージを送信するか
    reservation_canceled_for_patron: true

    # refs 2506 予約キャンセル時に管理者にキャンセル完了メッセージを送信するか
    reservation_canceled_for_library: true

    # refs 2506 予約資料確保時に予約者に資料確保完了メッセージを送信するか
    item_received_for_patron: true

    # refs 2506 予約資料確保時に管理者に資料確保完了メッセージを送信するか
    item_received_for_library: true

    # refs 2506 予約資料の有効期限が過ぎた時に利用者に有効期限切れメッセージを送信するか
    reservation_expired_for_patron: true

    # refs 2506 予約資料の有効期限が過ぎた時に管理者に有効期限切れメッセージを送信するか
    reservation_expired_for_library: true

    # refs 2506 貸出資料の督促送信指定日に利用者に督促メッセージを送信するか
    recall_item: true

    # refs 2506 貸出期限切れ資料の督促送信指定日に利用者に督促メッセージを送信するか
    recall_overdue_item: true

    # refs 2506 購入リクエストを受付時に利用者に受付完了メッセージを送信するか
    purchase_request_accepted: true

    # refs 2506 購入リクエスト謝絶時に利用者に謝絶完了メッセージを送信するか
    purchase_request_rejected: true

    # refs 3563 取置き済資料が貸出不可になったとき利用者に取置き取消メッセージを送信するか
    reserve_reverted_for_patron: true

    # refs 3563 取置き済資料が貸出不可になったとき管理者に取置き取消メッセージを送信するか
    reserve_reverted_for_library: true

  # 利用統計の帳票ファイル名
  statistic_report:
    monthly: "monthly_report.pdf"
    monthly_tsv: "monthly_report.tsv"
    daily: "daily_report.pdf"
    daily_tsv: "daily_report.tsv"
    timezone: "timezone_report.pdf"
    timezone_tsv: "timezone_report.tsv"
    day: "day_report.pdf"
    day_tsv: "day_report.tsv"
    age: "age_report.pdf"
    age_tsv: "age_report.tsv"
    items: "items_report.pdf"
    items_tsv: "items_report.tsv"
    inout_items: "inout_items_report.pdf"
    inout_items_tsv: "inout_items_report.tsv"
    loans: "loans_report.pdf"
    loans_tsv: "loans_report.tsv"
    groups: "groups_report.pdf"
    groups_tsv: "groups_report.tsv"
    departments: "departments_report.pdf"
    departments_tsv: "departments_report.tsv"
    # 時間別統計の設定
    open: 8
    hours: 14 

  # 検索結果一覧の出力(PDF)
  manifestation_list_print_pdf:
    filename: "manifestation_list.pdf"
  # 検索結果一覧の出力(TSV)
  manifestation_list_print_tsv:
    filename: "manifestation_list.tsv"
  # 検索結果一覧の出力(Excelx)
  manifestation_list_print_excelx:
    filename: "manifestation_list.xlsx"
    fontname: "ＭＳ ゴシック"
  # 欠号リストの一覧の出力(PDF)
  missing_list_print_pdf:
    filename: "missing_list.pdf"
  # 資料確認票のファイル名
  manifestation_locate_print:
    filename: "manifestation.pdf"

  # 貸出票の出力
  checkouts_print:
    filename: "checkouts.pdf"
    message: "本は大事に扱いましょう。期限はきちんと守りましょう。インターネットで延長ができます。"
  # 貸出リスト(PDF)の出力
  checkout_list_print_pdf:
    filename: "checkoutlist.pdf"
  # 貸出リスト(TSV)の出力
  checkout_list_print_tsv:
    filename: "checkoutlist.tsv"
  # 貸出リストに利用者の年齢を表示するかどうか
  checkout_print:
    old: true

  # 予約票の出力
  reserve_print:
    filename: "reserve.pdf"
    # 予約表に利用者の年齢を表示するかどうか
    old: true
  # 予約リスト(個人)の出力
  reserve_list_user_print:
    filename: "reserve_list_user.pdf"
  # 予約リスト(全体)の出力(PDF)
  reserve_list_all_print_pdf:
    filename: "reserve_list_all.pdf"
  # 予約リスト(全体)の出力(TSV)
  reserve_list_all_print_tsv:
    filename: "reserve_list_all.tsv"
  # 予約リスト(ピッキング用)の出力(PDF)
  reserve_list_picking_pdf:
    filename: "reserve_list_picking.pdf"
  # 取置済み資料の出力(PDF)
  retained_manifestation_list_print_pdf:
    filename: "retained_manifestation_list.pdf"
  # 取置済み資料の出力(TSV)
  retained_manifestation_list_print_tsv:
    filename: "retained_manifestation_list.tsv"

  # 利用者リストの出力(PDF)
  user_list_print_pdf:
    filename: "user_list.pdf"
  # 利用者リス知の出力(TSV)
  user_list_print_tsv:
    filename: "user_list.tsv"
  # 連絡不可者の出力(PDF)
  unable_list_print_pdf:
    filename: "unable_list.pdf"
  # 連絡不可者の出力(TSV)
  unable_list_print_tsv:
    filename: "unable_list.tsv"
  # 家族リストの出力(PDF)
  family_list_print_pdf:
    filename: "family_list.pdf"
  # 家族リストの出力(TSV)
  family_list_print_tsv:
    filename: "family_list.tsv"

  #購入リクエストの一覧の出力(TSV)
  purchase_requests_print_tsv:
    filename: "purchase_requests.tsv"
  # 督促はがきのファイル名
  reminder_postal_card_print:
    filename: "reminder_postal_card.pdf"
  # 督促はがきの図書館メッセージ（最大全角242文字）
  reminder_postal_card_message: "図書館からお借りになったなった本や視聴覚資料などを、返す日が過ぎております。\n速やかにお返しください。\n\n>・お返しになった後、行き違いにこの手紙が届きましたらご容赦ください。\n・図書館が閉まっているときは、入り口脇のブックポストをご利用ください。\n・視聴覚資料に限りましてはブックポストへの返却はご遠慮いただき、直接カウンターにお返しください。\n・資料を、郵送や宅配便でお返しいただく場合は、壊れないようご配慮の上お送りください。\n・ご不明な点がありましたらお問い合わせください。"
  # 督促書のファイル名
  reminder_letter_print:
    filename: "reminder_letter.pdf"
  # 督促書の図書館メッセージ
  reminder_letter_message: "図書館からお借りになったなった本や視聴覚資料などを、返す日が過ぎております。\n速やかにお返しください。\n\n・お返しになった後、行き違いにこの手紙が届きましたらご容赦ください。\n・図書館が閉まっているときは、入り口脇のブックポストをご利用ください。\n・視聴覚資料に限りましてはブックポストへの返却はご遠慮いただき、直接カウンターにお返しください。\n・資料を、郵送や宅配便でお返しいただく場合は、壊れないようご配慮の上お送りください。\n・ご不明な点がありましたらお問い合わせください。"
  # 督促情報表のファイル名
  reminder_list_print_pdf:
    filename: "reminder_list.pdf"
  # 自動で督促メールを送る延滞日数
  auto_reminder_period: 5

  # 督促情報表のファイル名
  reminder_list_print_tsv:
    filename: "reminder_list.tsv"

  #開館日と催し物の一覧の出力(TSV)
  event_list_print_tsv:
    filename: "event_list.tsv"

  # 貸出状況の帳票ファイル名
  checkoutlist_report_pdf:
    filename: "checkoutlist.pdf"
  checkoutlist_report_tsv:
    filename: "checkoutlist.tsv"

  # 予約状況の帳票ファイル名
  reservelist_report_pdf:
    filename: "reservelist.pdf"
  reservelist_report_tsv:
    filename: "reservelist.tsv"

  # TSVファイルからの資料インポートの結果の一覧の出力(TSV)
  resource_import_results_print_tsv:
    filename: "resource_import_results.tsv"

  # テキストファイルからの資料インポートの結果の一覧の出力(TSV)
  resource_import_textresults_print_tsv:
    filename: "resource_import_textresults.tsv"
  # 催し物インポートの結果の一覧の出力(TSV)
  event_import_results_print_tsv:
    filename: "event_import_results.tsv"
  # 人物・団体インポートの結果の一覧の出力(TSV)
  patron_import_results_print_tsv:
    filename: "patron_import_results.tsv"
  # テキストファイルからの資料インポートの結果の一覧の出力(XLSX)
  resource_import_textresults_print_xlsx:
    filename: "resource_import_textresults.xlsx"

  # 利用者別貸出統計の出力(TSV)
  user_checkout_stats_print_tsv:
    filename: "user_checkout_stats.tsv"
  # 利用者別予約統計の出力(TSV)
  user_reserve_stats_print_tsv:
    filename: "user_reserve_stats.tsv"
  # 資料別貸出統計の出力(TSV)
  manifestation_checkout_stats_print_tsv:
    filename: "manifestation_checkout_stats.tsv"
  # 資料者別予約統計の出力(TSV)
  manifestation_reserve_stats_print_tsv:
    filename: "manifestation_reserve_stats.tsv"
  # ブックマーク統計の出力(TSV)
  bookmark_stat_stats_print_tsv:
    filename: "bookmark_stat_stats.tsv"

  # 資料の詳細画面に過去の貸出回数を表示
  manifestation:
    display_checkouts_count: true
    display_reserves_count: true
    display_last_checkout_datetime: true
    # 正副本管理をするか
    manage_item_rank: true

  # 利用者一覧の色別表示
  user:
    locked:
      background: "aqua"
    unable:
      background: "yellow"
  
  # refs 1991 雑誌最新号の貸出禁止
  checkouts:
    cannot_for_new_serial: true

  # refs 1989 trueの場合 => itemがひとつだけのmanifestationのitemを削除するとき、除籍してからのみ削除できる
  items:
    confirm_destroy: true

  # refs 2588 所蔵のない資料の予約
  reserves:
    able_for_not_item: true

  # refs 1978 拡張統計-図書リストの新刊購入受入リスト 出版日がシステム日付からn日前以降であるものを抽出
  new_book_term: 14

  # refs 3127 ユーザー権限以下でログイン時、購入リクエスト画面を表示するかどうか。trueのとき表示
  user_show_purchase_requests: true

  # refs 3127 ユーザー権限以下でログイン時、質問(レファレンス)ト画面を表示するかどうか。trueのとき表示
  user_show_questions: true

  # refs 3128 発注リストを使用するかどうか。trueのとき使用可能
  use_order_lists: true

  # 書影
  manifestation_book_jacket:
    unknown_resource: "(NO IMAGE)"
  
  # 請求記号の先頭文字がセパレータのとき先頭文字を削除するか
  items:
    call_number:
      delete_first_delimiter: true
    # refs 1989 trueの場合 => itemがひとつだけのmanifestationのitemを削除するとき、除籍してからのみ削除できる
    confirm_destroy: true
 
  # refs 3861資料の検索時、キーワードがスペースで区切られている場合はそれぞれの語によってAND検索を行うか
  search:
    use_and: true

  # 音
  sounds:
    basedir: "sounds/"
    errors:
      default: "missA11.ogg"
      item:
        this_item_is_reserved: "missA11.ogg"
      checkin:
        not_checkin: "chimeA08.ogg"
        already_checked_in: "missA11.ogg"
        overdue_item: "missA11.ogg"
        not_available_for_checkin: "churchA08.ogg"
        other_library_item: "chimeA08.ogg"
      checked_item:
        already_checked_out: "missA11.ogg"
        not_available_for_checkout: "churchA08.ogg"
        this_group_cannot_checkout: "churchA08.ogg"
        in_transcation: "chimeA08.ogg"
        reserved_item_included: "chimeA08.ogg"
      checkout:
        this_item_is_reserved: "chimeA08.ogg"
        over_renewal_limit: "chimeA08.ogg"
        you_have_overdue_item: "chimeA08.ogg"

  # refs 1849 trueの場合=>一般利用者において、在架資料は、図書館利用時に借りることができる。
  # 予約対象は貸出中の図書のみ
  reserve:
    not_reserve_on_loan: false

  # refs 2042 蔵書点検時、未返却資料を検出した場合は自動的に返却処理を行う
  library_checks:
    auto_checkin: true

  # 蔵書点検
  libcheck_test_do_notfound: true # set false if you want to don't check not_found items
  libcheck_notfound_with_title_cout: 10000
  libcheck_shelf_barcode_len: 12
  libcheck_outskirts_count: 3
  libcheck_ndc_check: ["book"]
  libcheck_serial_name: "serial"
  libcheck_serial: ["serial"]

  # refs 2553 ユーザ情報重複チェック機能
  patron:
    check_duplicate_user: false

  standaloneclient:
    # refs 2552 クライアント接続パスフレーズ
    clientkey: "Next-L/Enju:Next-L/Enju:Next-L/E"
    # refs 2552 データを暗号化する
    encoding: false

  # 業務用サーバ(貸出・返却・予約可)
  operation: true

  # 未返却資料を貸出処理読み込んだ場合、再貸出可能にする
  checkout:
    auto_checkin: true
 
  # インポート時取込可能なファイル形式を設定する
  # カンマ,区切りで利用可能アダプタを指定する
  resource_adapters: Excelfile_Adapter, Tsvfile_Adapter

  # 利用者番号とユーザ名を同じ値にする
  auto_user_number: true

  # 書誌リストの各種フォーマット出力でレコード件数が500より多ければバックグラウンド処理とする
  background_job:
    threshold:
      export: 500
 
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

